version: '3'
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


#cd C:\Users\kolos.gv.PARTNER\Desktop\HomeSpring\3.1\demo\demo\docker
#docker-compose up --Собирает образ
#docker container ls -a --Отображает заведенные образы
#docker container rm 3e5a64147762 -f Закрывает образ

