version: '3'
services:
  postgres:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


#docker-compose up --Собирает образ
#docker container ls -a --Отображает заведенные образы
#docker container rm 3e5a64147762 -f Закрывает образ
#docker-compose down  # Stop container on current dir if there is a docker-compose.yml
#  cd docker

